DOMAIN = "seoul_bus"
CONF_STATION_ID = "station_id"
CONF_STATION_NAME = "station_name"
CONF_START_TIME = "start_time"
CONF_END_TIME = "end_time"
CONF_API_ISSUED_DATE = "api_issued_date"
CONF_INCLUDE_BUSES = "include_buses"
